### ISSUE TITLE
AjaxAction Class use!

### ISSUE THREAD

**Issue by ozarraga** [jlorente/yii2-datatables#1]
Have a nice day.

I don´t have any idea how to use AjaxAction class to get response from the server, when I use "serverSide" option.

I don´t have any idea about use any other class to symplify the use of te widget. I had to build my own script of server action response.

The widget is fabulous but once i execute the action from pagination or search, the widget initial configuration efect including serials and action columns is lost.

Could you please add some more help with more verbose examples?
I think you are in a good way with the bundle, but I cannot understand how use it in more effectively mode as the basic mode.

(Sorry for my english)

**Comment by garrettw** [comment]
I had to figure out how to use this library on my own as well, so I can help.

First, figure out a URL where you want the AJAX endpoint to live. For example, if you put it at `/api/datatables`, then you should have a controller called `ApiController`, and in that class you will need a method called `actions()` that returns an array. (This method is used to define external actions whose code comes from outside of the controller class.)

In the array that your `actions()` method returns, you would add:
```
'datatables' => [
    'class' => \jlorente\datatables\actions\AjaxAction::class,
    'dataTablesModelInterface' => new YourModelSearch(),
]
```
where `YourModelSearch` is the name of the search model class you've created to go with the main model class you're using.

In the '`clientOptions'` for the widget, you would just need:
```
    'serverSide' => true,
    'ajax' => '/api/datatables',
```

Now, your search model class will be a little different than usual.
First, it needs to implement `jlorente\datatables\models\DataTablesModelInterface`, which requires you to define 4 new methods as follows.

- `getColumns()` - should return an array of the columns like you would normally pass into a GridView widget. In fact, I made sure to pass the search model into my view, so I just give the widget `'columns' => $searchModel->getColumns()` so as to keep everything defined in one place. I'll show how I passed it in later.
- `getDataProvider()` - should contain: (replace `YourModel` with the name of your model class)
```php
return new \jlorente\datatables\data\ActiveDataProvider([
    'query' => YourModel::find(),
    'sort' => ['attributes' => $this->getSortAttributes()],
]);
```
- `getSortAttributes()` - should return an array of sort attributes like you would normally pass to a data provider.
- `searchFree($query, $value)` - should modify the `$query` by adding `where` clauses and such to control the search behavior of the global search field. For example, if you just want to search every column for the search string, you would just do something like:
```php
$query->where([
    'or',
    ['like', 'id', $value],
    ['like', 'name', $value],
    ['like', 'user_name', $value],
    ['like', 'location', $value],
    ...
]);
```

Lastly, the controller action method for the page that will contain the table should look something like this:
```php
    public function actionTable()
    {
        $searchModel = new \jlorente\datatables\models\SearchModel([
            'searchModel' => new YourModelSearch(),
        ]);
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('table', [
            'searchModel' => $searchModel->getSearchModel(),
            'dataProvider' => $dataProvider,
        ]);
    }
```
